export enum ErrorCode {
  INVALID_MESSAGE = "INVALID_MESSAGE",
  ROOM_FULL = "ROOM_FULL",
  NOT_HOST = "NOT_HOST",
  GAME_ALREADY_STARTED = "GAME_ALREADY_STARTED",
  GAME_NOT_STARTED = "GAME_NOT_STARTED",
  INSUFFICIENT_PLAYERS = "INSUFFICIENT_PLAYERS",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  INVALID_ACTION = "INVALID_ACTION",
}

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
}
