export enum ErrorCode {
  INVALID_MESSAGE = "INVALID_MESSAGE",
  ROOM_FULL = "ROOM_FULL",
  NOT_HOST = "NOT_HOST",
  GAME_ALREADY_STARTED = "GAME_ALREADY_STARTED",
  GAME_NOT_STARTED = "GAME_NOT_STARTED",
  INSUFFICIENT_PLAYERS = "INSUFFICIENT_PLAYERS",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  INVALID_ACTION = "INVALID_ACTION",
  /** 强制暗标补开未完成，不可跳过结算 */
  DARK_BID_REQUIRED = "DARK_BID_REQUIRED",
  /** Round 开始必须先翻 1 张事件牌 */
  EVENT_FLIP_REQUIRED = "EVENT_FLIP_REQUIRED",
  /** C-14 响应窗不可跳过 */
  C14_RESPONSE_REQUIRED = "C14_RESPONSE_REQUIRED",
  /** C-12 仅可甩个人债/Bug */
  PUBLIC_DEBT_REJECTED = "PUBLIC_DEBT_REJECTED",
  WRONG_PHASE = "WRONG_PHASE",
  NOT_YOUR_TURN = "NOT_YOUR_TURN",
  /** 联机加入缺少可交换的 Steam 会话票据（开发模式不返回此码） */
  AUTH_REQUIRED = "AUTH_REQUIRED",
  /** 会话票据被 Steam Web API 拒绝，或票据格式无效 */
  AUTH_FAILED = "AUTH_FAILED",
}

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
}
